services:
  mediawiki:
    image: mediawiki
    container_name: mediawiki
    restart: always
    networks:
      - db-con
      - reverse-proxy
    volumes:
      - mediawiki-images:/var/www/html/images
      - ./LocalSettings.php:/var/www/html/LocalSettings.php
      - ./secrets.php:/var/www/html/secrets.php
      - ./logo.svg:/var/www/html/resources/assets/logo.svg
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mediawiki.rule=Host(`wiki.rotarypub.se`)"
      - "traefik.http.routers.mediawiki.entrypoints=websecure"
      - "traefik.http.routers.mediawiki.middlewares=auth@file"
      

volumes:
  mediawiki-images:

networks:
  db-con:
    external: true
  reverse-proxy:
    external: true
